name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Compile exe
        run: |
          pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          pip install pyinstaller pynput
          pyinstaller --onefile --noconsole main.py

      # 换成官方制品，不会报release权限错误
      - name: Export EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe-file
          path: dist/main.exe
